### ISSUE TITLE
wx.onHCEMessage触发不了

### ISSUE THREAD

**Issue by k365266378** [redchenjs/nfc_attendance_system_weixin#1]
请问下您用的是什么读卡器。

**Comment by redchenjs** [comment]
> 请问下您用的是什么读卡器。

PN532，另外这个小程序是[NFC考勤系统](https://github.com/redchenjs/nfc_attendance_system)项目组的一部分，故设计使用了特定的AID用于设备间识别与通信，理论上`wx.onHCEMessage`是不会被任何其他装置触发的。
